// <auto-generated />
namespace MartaShop.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20210291313324_Intial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210291313324_Intial));
        
        string IMigrationMetadata.Id
        {
            get { return "202107301852324_20210291313324_Intial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
